module WordyGame {

  typedef sequence<string> StringSeq;

  enum CredentialsResult {SUCCESS, INVALID_CREDENTIALS, ACCOUNT_ALREADY_LOGGED_IN, USERNAME_TAKEN, SERVER_UNAVAILABLE};
  enum WordValidation{WORD_LESS_THAN_FIVE_LETTERS, INVALID_WORD, VALID_WORD};


  struct WordyGamePlayer {
    long id;
    long wins;
  };

  struct Game {
    string gameID;
    string status;
    WordyGamePlayer host;
    WordyGamePlayer winner;
  };

  interface WordyGameServer {
    CredentialsResult login(in string username, in string password); // Connect
    void logout(in string username);
    Game playGame(in WordyGamePlayer username);
    WordValidation checkWord(in string word);

    StringSeq getLongestWords();
    StringSeq getTopPlayers();
  };

  exception NoPlayersAvailable {
    string reason;
  };

  exception InvalidWord {
    string reason;
  };

  exception LoginFailed{
    string reason;
  };
};
