module WordyGame {

  struct TopWord{
    string username;
    string word;
  };

  struct TopPlayer {
    long rank;
    string username;
    long wins;
  };

  typedef sequence<TopWord> TopWords;
  typedef sequence<TopPlayer> TopPlayers;
  typedef sequence<char> letters;

  struct WordyGamePlayer {
    long id;
    long wins;
    string gameID;
    string status; // ready or not
  };

  struct Game {
    string gameID;
    string status;
    WordyGamePlayer host;
    WordyGamePlayer winner;
  };

  interface WordyGameServer {
    void login(in string username, in string password) exception InvalidCredentials, exception UserAlreadyLoggedIn, exception InvalidPassword, exception ServerUnavailable;
    void logout(in long userID);
    string playGame(in long userID) exception NoPlayersAvailable;
    void checkWord(in string word, in string gameID, in string username) exception InvalidWord, WordLessThanFiveLetters;
    letters requestLetters(in string gameID);
    string checkWinner(in string gameID);
    boolean roundStatus(in string gameID);

    TopWords getLongestWords();
    TopPlayers getTopPlayers();
  };

  exception NoPlayersAvailable {
    string reason;
  };

  exception UserAlreadyLoggedIn{
    string reason;
  };

  exception InvalidCredentials{
    string reason;
  };

  exception InvalidPassword{
    string reason;
  };

  exception ServerUnavailable {
    string reason;
  };

  exception InvalidWord {
    string reason;
  };

  exception WordLessThanFiveLetters{
    string reason;
  };

};
