package WordyGame;

/**
* WordyGame/CredentialsResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Thursday, April 27, 2023 10:09:34 PM SGT
*/

public final class CredentialsResultHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame.CredentialsResult value = null;

  public CredentialsResultHolder ()
  {
  }

  public CredentialsResultHolder (WordyGame.CredentialsResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGame.CredentialsResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGame.CredentialsResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGame.CredentialsResultHelper.type ();
  }

}
