package WordyGame;


/**
* WordyGame/CredentialsResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:54:21 AM SGT
*/

public class CredentialsResult implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static WordyGame.CredentialsResult[] __array = new WordyGame.CredentialsResult [__size];

  public static final int _SUCCESS = 0;
  public static final WordyGame.CredentialsResult SUCCESS = new WordyGame.CredentialsResult(_SUCCESS);
  public static final int _INVALID_CREDENTIALS = 1;
  public static final WordyGame.CredentialsResult INVALID_CREDENTIALS = new WordyGame.CredentialsResult(_INVALID_CREDENTIALS);
  public static final int _ACCOUNT_ALREADY_LOGGED_IN = 2;
  public static final WordyGame.CredentialsResult ACCOUNT_ALREADY_LOGGED_IN = new WordyGame.CredentialsResult(_ACCOUNT_ALREADY_LOGGED_IN);
  public static final int _USERNAME_TAKEN = 3;
  public static final WordyGame.CredentialsResult USERNAME_TAKEN = new WordyGame.CredentialsResult(_USERNAME_TAKEN);
  public static final int _SERVER_UNAVAILABLE = 4;
  public static final WordyGame.CredentialsResult SERVER_UNAVAILABLE = new WordyGame.CredentialsResult(_SERVER_UNAVAILABLE);

  public int value ()
  {
    return __value;
  }

  public static WordyGame.CredentialsResult from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CredentialsResult (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CredentialsResult
