package WordyGame;

/**
* WordyGame/ExceededTimeLimitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Friday, April 28, 2023 8:59:44 PM SGT
*/

public final class ExceededTimeLimitHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame.ExceededTimeLimit value = null;

  public ExceededTimeLimitHolder ()
  {
  }

  public ExceededTimeLimitHolder (WordyGame.ExceededTimeLimit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGame.ExceededTimeLimitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGame.ExceededTimeLimitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGame.ExceededTimeLimitHelper.type ();
  }

}
