package WordyGame;

/**
* WordyGame/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Thursday, April 27, 2023 10:09:34 PM SGT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (WordyGame.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGame.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGame.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGame.GameHelper.type ();
  }

}
