package WordyGame;


import java.util.ArrayList;
import java.util.Timer;

/**
* WordyGame/Game.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Thursday, April 27, 2023 10:09:34 PM SGT
*/

public final class Game implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String status = null;
  public WordyGame.WordyGamePlayer host = null;
  public WordyGame.WordyGamePlayer winner = null;
  public ArrayList<WordyGamePlayer> players = new ArrayList<>();
  public Timer timer = new Timer();

  public Game ()
  {
  } // ctor

  public Game (String _gameID, String _status, WordyGame.WordyGamePlayer _host, WordyGame.WordyGamePlayer _winner)
  {
    gameID = _gameID;
    status = _status;
    host = _host;
    winner = _winner;
  } // ctor

  public Game(WordyGamePlayer hostPlayer) {
    host = hostPlayer;
    players.add(hostPlayer);
    status = "Waiting";
    winner = new WordyGamePlayer();
    gameID = "1";


//    timer.schedule(new tenSecondTimer(), 10*1000);
  }

} // class Game
