package WordyGame;


/**
* WordyGame/GameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Wednesday, May 10, 2023 11:56:33 AM SGT
*/

abstract public class GameHelper
{
  private static String  _id = "IDL:WordyGame/Game:1.0";

  public static void insert (org.omg.CORBA.Any a, WordyGame.Game that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static WordyGame.Game extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "gameID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "status",
            _tcOf_members0,
            null);
          _tcOf_members0 = WordyGame.WordyGamePlayerHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "host",
            _tcOf_members0,
            null);
          _tcOf_members0 = WordyGame.WordyGamePlayerHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "winner",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (WordyGame.GameHelper.id (), "Game", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static WordyGame.Game read (org.omg.CORBA.portable.InputStream istream)
  {
    WordyGame.Game value = new WordyGame.Game ();
    value.gameID = istream.read_long ();
    value.status = istream.read_string ();
    value.host = WordyGame.WordyGamePlayerHelper.read (istream);
    value.winner = WordyGame.WordyGamePlayerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, WordyGame.Game value)
  {
    ostream.write_long (value.gameID);
    ostream.write_string (value.status);
    WordyGame.WordyGamePlayerHelper.write (ostream, value.host);
    WordyGame.WordyGamePlayerHelper.write (ostream, value.winner);
  }

}
