package WordyGame;


/**
* WordyGame/InvalidPassword.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Friday, April 28, 2023 8:59:44 PM SGT
*/

public final class InvalidPassword extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidPassword ()
  {
    super(InvalidPasswordHelper.id());
  } // ctor

  public InvalidPassword (String _reason)
  {
    super(InvalidPasswordHelper.id());
    reason = _reason;
  } // ctor


  public InvalidPassword (String $reason, String _reason)
  {
    super(InvalidPasswordHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidPassword
