package WordyGame;


/**
* WordyGame/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Friday, May 12, 2023 8:08:15 AM CST
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  } // ctor

  public InvalidCredentials (String _reason)
  {
    super(InvalidCredentialsHelper.id());
    reason = _reason;
  } // ctor


  public InvalidCredentials (String $reason, String _reason)
  {
    super(InvalidCredentialsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidCredentials
