package WordyGame;

/**
* WordyGame/LobbyStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:50:14 AM SGT
*/

public final class LobbyStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public LobbyStatus value = null;

  public LobbyStatusHolder ()
  {
  }

  public LobbyStatusHolder (LobbyStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LobbyStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LobbyStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LobbyStatusHelper.type ();
  }

}
