package WordyGame;

/**
* WordyGame/LobbyStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:54:21 AM SGT
*/

public final class LobbyStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame.LobbyStatus value = null;

  public LobbyStatusHolder ()
  {
  }

  public LobbyStatusHolder (WordyGame.LobbyStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGame.LobbyStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGame.LobbyStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGame.LobbyStatusHelper.type ();
  }

}
