package WordyGame;


/**
* WordyGame/LoginFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Thursday, April 27, 2023 10:09:34 PM SGT
*/

public final class LoginFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public LoginFailed ()
  {
    super(LoginFailedHelper.id());
  } // ctor

  public LoginFailed (String _reason)
  {
    super(LoginFailedHelper.id());
    reason = _reason;
  } // ctor


  public LoginFailed (String $reason, String _reason)
  {
    super(LoginFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class LoginFailed
