package WordyGame;

/**
* WordyGame/LoginFailedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:50:14 AM SGT
*/

public final class LoginFailedHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginFailed value = null;

  public LoginFailedHolder ()
  {
  }

  public LoginFailedHolder (LoginFailed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginFailedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginFailedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginFailedHelper.type ();
  }

}
