package WordyGame;

/**
* WordyGame/ServerUnavailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Friday, April 28, 2023 8:59:44 PM SGT
*/

public final class ServerUnavailableHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame.ServerUnavailable value = null;

  public ServerUnavailableHolder ()
  {
  }

  public ServerUnavailableHolder (WordyGame.ServerUnavailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGame.ServerUnavailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGame.ServerUnavailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGame.ServerUnavailableHelper.type ();
  }

}
