package WordyGame;


/**
* WordyGame/TopPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Wednesday, May 10, 2023 11:56:33 AM SGT
*/

public final class TopPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame.TopPlayer value[] = null;

  public TopPlayersHolder ()
  {
  }

  public TopPlayersHolder (WordyGame.TopPlayer[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGame.TopPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGame.TopPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGame.TopPlayersHelper.type ();
  }

}
