package WordyGame;

/**
* WordyGame/WordValidationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:50:14 AM SGT
*/

public final class WordValidationHolder implements org.omg.CORBA.portable.Streamable
{
  public WordValidation value = null;

  public WordValidationHolder ()
  {
  }

  public WordValidationHolder (WordValidation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordValidationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordValidationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordValidationHelper.type ();
  }

}
