package WordyGame;


/**
* WordyGame/WordyGamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:50:14 AM SGT
*/

public final class WordyGamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int wins = (int)0;

  public WordyGamePlayer ()
  {
  } // ctor

  public WordyGamePlayer (int _id, int _wins)
  {
    id = _id;
    wins = _wins;
  } // ctor

} // class WordyGamePlayer
