package WordyGame;


/**
* WordyGame/WordValidation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:50:14 AM SGT
*/

public class WordValidation implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static WordValidation[] __array = new WordValidation [__size];

  public static final int _WORD_LESS_THAN_FIVE_LETTERS = 0;
  public static final WordValidation WORD_LESS_THAN_FIVE_LETTERS = new WordValidation(_WORD_LESS_THAN_FIVE_LETTERS);
  public static final int _INVALID_WORD = 1;
  public static final WordValidation INVALID_WORD = new WordValidation(_INVALID_WORD);

  public int value ()
  {
    return __value;
  }

  public static WordValidation from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected WordValidation (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class WordValidation
