package WordyGame;


/**
* WordyGame/WordValidationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Sunday, April 23, 2023 11:50:14 AM SGT
*/

abstract public class WordValidationHelper
{
  private static String  _id = "IDL:WordyGame/WordValidation:1.0";

  public static void insert (org.omg.CORBA.Any a, WordValidation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static WordValidation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (WordValidationHelper.id (), "WordValidation", new String[] { "WORD_LESS_THAN_FIVE_LETTERS", "INVALID_WORD"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static WordValidation read (org.omg.CORBA.portable.InputStream istream)
  {
    return WordValidation.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, WordValidation value)
  {
    ostream.write_long (value.value ());
  }

}
