package WordyGame;


/**
* WordyGame/WordyGamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Thursday, May 4, 2023 4:03:30 PM SGT
*/

public final class WordyGamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int wins = (int)0;
  public int gameID = (int)0;
  public String status = null;

  public WordyGamePlayer ()
  {
  } // ctor

  public WordyGamePlayer (int _id, int _wins, int _gameID, String _status)
  {
    id = _id;
    wins = _wins;
    gameID = _gameID;
    status = _status;
  } // ctor

} // class WordyGamePlayer
