package WordyGame;


/**
* WordyGame/WordyGameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Saturday, April 29, 2023 11:49:54 AM SGT
*/

public interface WordyGameServerOperations 
{
  void login (String username, String password) throws WordyGame.InvalidCredentials, WordyGame.UserAlreadyLoggedIn, WordyGame.InvalidPassword, WordyGame.ServerUnavailable;
  void logout (int userID);
  int playGame (int userID) throws WordyGame.NoPlayersAvailable;
  String ready (int userID, int gameID);
  void checkWord (String word, int gameID, int userID) throws WordyGame.InvalidWord, WordyGame.WordLessThanFiveLetters, WordyGame.ExceededTimeLimit;
  char[] requestLetters (String gameID);
  String checkWinner (String gameID);
  boolean roundStatus (String gameID);
  WordyGame.TopWord[] getLongestWords ();
  WordyGame.TopPlayer[] getTopPlayers ();
} // interface WordyGameServerOperations
