package WordyGame;


/**
* WordyGame/WordyGamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Friday, April 28, 2023 8:59:44 PM SGT
*/

public final class WordyGamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int wins = (int)0;
  public String gameID = null;
  public String status = null;

  public WordyGamePlayer ()
  {
  } // ctor

  public WordyGamePlayer (int _id, int _wins, String _gameID, String _status)
  {
    id = _id;
    wins = _wins;
    gameID = _gameID;
    status = _status;
  } // ctor

} // class WordyGamePlayer
