package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/CredentialsResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public class CredentialsResult implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static com.java.fingrp7_java.Server.WordyGame.CredentialsResult[] __array = new com.java.fingrp7_java.Server.WordyGame.CredentialsResult [__size];

  public static final int _SUCCESS = 0;
  public static final com.java.fingrp7_java.Server.WordyGame.CredentialsResult SUCCESS = new com.java.fingrp7_java.Server.WordyGame.CredentialsResult(_SUCCESS);
  public static final int _INVALID_CREDENTIALS = 1;
  public static final com.java.fingrp7_java.Server.WordyGame.CredentialsResult INVALID_CREDENTIALS = new com.java.fingrp7_java.Server.WordyGame.CredentialsResult(_INVALID_CREDENTIALS);
  public static final int _ACCOUNT_ALREADY_LOGGED_IN = 2;
  public static final com.java.fingrp7_java.Server.WordyGame.CredentialsResult ACCOUNT_ALREADY_LOGGED_IN = new com.java.fingrp7_java.Server.WordyGame.CredentialsResult(_ACCOUNT_ALREADY_LOGGED_IN);
  public static final int _USERNAME_TAKEN = 3;
  public static final com.java.fingrp7_java.Server.WordyGame.CredentialsResult USERNAME_TAKEN = new com.java.fingrp7_java.Server.WordyGame.CredentialsResult(_USERNAME_TAKEN);
  public static final int _SERVER_UNAVAILABLE = 4;
  public static final com.java.fingrp7_java.Server.WordyGame.CredentialsResult SERVER_UNAVAILABLE = new com.java.fingrp7_java.Server.WordyGame.CredentialsResult(_SERVER_UNAVAILABLE);

  public int value ()
  {
    return __value;
  }

  public static com.java.fingrp7_java.Server.WordyGame.CredentialsResult from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CredentialsResult (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CredentialsResult
