package com.java.fingrp7_java.Server.WordyGame;

/**
* com.java.fingrp7_java.Server.WordyGame/CredentialsResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public final class CredentialsResultHolder implements org.omg.CORBA.portable.Streamable
{
  public com.java.fingrp7_java.Server.WordyGame.CredentialsResult value = null;

  public CredentialsResultHolder ()
  {
  }

  public CredentialsResultHolder (com.java.fingrp7_java.Server.WordyGame.CredentialsResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.java.fingrp7_java.Server.WordyGame.CredentialsResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.java.fingrp7_java.Server.WordyGame.CredentialsResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.java.fingrp7_java.Server.WordyGame.CredentialsResultHelper.type ();
  }

}
