package com.java.fingrp7_java.Server.WordyGame;

/**
* com.java.fingrp7_java.Server.WordyGame/NoPlayersAvailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public final class NoPlayersAvailableHolder implements org.omg.CORBA.portable.Streamable
{
  public com.java.fingrp7_java.Server.WordyGame.NoPlayersAvailable value = null;

  public NoPlayersAvailableHolder ()
  {
  }

  public NoPlayersAvailableHolder (com.java.fingrp7_java.Server.WordyGame.NoPlayersAvailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.java.fingrp7_java.Server.WordyGame.NoPlayersAvailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.java.fingrp7_java.Server.WordyGame.NoPlayersAvailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.java.fingrp7_java.Server.WordyGame.NoPlayersAvailableHelper.type ();
  }

}
