package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/NoPlayersAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public final class NoPlayersAvailable extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NoPlayersAvailable ()
  {
    super(NoPlayersAvailableHelper.id());
  } // ctor

  public NoPlayersAvailable (String _reason)
  {
    super(NoPlayersAvailableHelper.id());
    reason = _reason;
  } // ctor


  public NoPlayersAvailable (String $reason, String _reason)
  {
    super(NoPlayersAvailableHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NoPlayersAvailable
