package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/WordyGameServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

abstract public class WordyGameServerHelper
{
  private static String  _id = "IDL:com.java.fingrp7_java.Server.WordyGame/WordyGameServer:1.0";

  public static void insert (org.omg.CORBA.Any a, com.java.fingrp7_java.Server.WordyGame.WordyGameServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordyGameServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.java.fingrp7_java.Server.WordyGame.WordyGameServerHelper.id (), "WordyGameServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordyGameServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WordyGameServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.java.fingrp7_java.Server.WordyGame.WordyGameServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordyGameServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.java.fingrp7_java.Server.WordyGame.WordyGameServer)
      return (com.java.fingrp7_java.Server.WordyGame.WordyGameServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.java.fingrp7_java.Server.WordyGame._WordyGameServerStub stub = new com.java.fingrp7_java.Server.WordyGame._WordyGameServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordyGameServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.java.fingrp7_java.Server.WordyGame.WordyGameServer)
      return (com.java.fingrp7_java.Server.WordyGame.WordyGameServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.java.fingrp7_java.Server.WordyGame._WordyGameServerStub stub = new com.java.fingrp7_java.Server.WordyGame._WordyGameServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
