package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/WordyGamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public final class WordyGamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public WordyGamePlayer ()
  {
  } // ctor

  public WordyGamePlayer (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class WordyGamePlayer
