package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/WordValidationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

abstract public class WordValidationHelper
{
  private static String  _id = "IDL:com.java.fingrp7_java.Server.WordyGame/WordValidation:1.0";

  public static void insert (org.omg.CORBA.Any a, com.java.fingrp7_java.Server.WordyGame.WordValidation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordValidation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.java.fingrp7_java.Server.WordyGame.WordValidationHelper.id (), "WordValidation", new String[] { "WORD_LESS_THAN_FIVE_LETTERS", "INVALID_WORD"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordValidation read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.java.fingrp7_java.Server.WordyGame.WordValidation.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.java.fingrp7_java.Server.WordyGame.WordValidation value)
  {
    ostream.write_long (value.value ());
  }

}
