package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/WordyGameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public interface WordyGameServerOperations 
{
  com.java.fingrp7_java.Server.WordyGame.CredentialsResult login (String username, String password) throws NoPlayersAvailable;

  // Connect
  com.java.fingrp7_java.Server.WordyGame.CredentialsResult signUp ();

  // 1
  void logout (String username);
  String[] playGame (String username) throws NoPlayersAvailable;
  boolean checkWord (String word);
  String[] getLongestWords ();
  String[] getTopPlayers ();
} // interface WordyGameServerOperations
