package com.java.fingrp7_java.Server.WordyGame;


/**
* com.java.fingrp7_java.Server.WordyGame/WordValidation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public class WordValidation implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.java.fingrp7_java.Server.WordyGame.WordValidation[] __array = new com.java.fingrp7_java.Server.WordyGame.WordValidation [__size];

  public static final int _WORD_LESS_THAN_FIVE_LETTERS = 0;
  public static final com.java.fingrp7_java.Server.WordyGame.WordValidation WORD_LESS_THAN_FIVE_LETTERS = new com.java.fingrp7_java.Server.WordyGame.WordValidation(_WORD_LESS_THAN_FIVE_LETTERS);
  public static final int _INVALID_WORD = 1;
  public static final com.java.fingrp7_java.Server.WordyGame.WordValidation INVALID_WORD = new com.java.fingrp7_java.Server.WordyGame.WordValidation(_INVALID_WORD);

  public int value ()
  {
    return __value;
  }

  public static com.java.fingrp7_java.Server.WordyGame.WordValidation from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected WordValidation (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class WordValidation
