package com.java.fingrp7_java.Server.WordyGame;

/**
* com.java.fingrp7_java.Server.WordyGame/WordyGameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com.java.fingrp7_java.Server.WordyGame.idl
* Tuesday, April 18, 2023 11:22:51 AM CST
*/

public final class WordyGameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.java.fingrp7_java.Server.WordyGame.WordyGameServer value = null;

  public WordyGameServerHolder ()
  {
  }

  public WordyGameServerHolder (com.java.fingrp7_java.Server.WordyGame.WordyGameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.java.fingrp7_java.Server.WordyGame.WordyGameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.java.fingrp7_java.Server.WordyGame.WordyGameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.java.fingrp7_java.Server.WordyGame.WordyGameServerHelper.type ();
  }

}
