package com.java.fingrp7_java.Client.WordyGameClient;

/**
* WordyGameClient/LoginResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

public final class LoginResultHolder implements org.omg.CORBA.portable.Streamable
{
  public com.java.fingrp7_java.Client.WordyGameClient.LoginResult value = null;

  public LoginResultHolder ()
  {
  }

  public LoginResultHolder (com.java.fingrp7_java.Client.WordyGameClient.LoginResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.java.fingrp7_java.Client.WordyGameClient.LoginResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.java.fingrp7_java.Client.WordyGameClient.LoginResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.java.fingrp7_java.Client.WordyGameClient.LoginResultHelper.type ();
  }

}
