package com.java.fingrp7_java.Client.WordyGameClient;


/**
* WordyGameClient/LoginResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

public class LoginResult implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static com.java.fingrp7_java.Client.WordyGameClient.LoginResult[] __array = new com.java.fingrp7_java.Client.WordyGameClient.LoginResult [__size];

  public static final int _SUCCESS = 0;
  public static final com.java.fingrp7_java.Client.WordyGameClient.LoginResult SUCCESS = new com.java.fingrp7_java.Client.WordyGameClient.LoginResult(_SUCCESS);
  public static final int _INVALID_CREDENTIALS = 1;
  public static final com.java.fingrp7_java.Client.WordyGameClient.LoginResult INVALID_CREDENTIALS = new com.java.fingrp7_java.Client.WordyGameClient.LoginResult(_INVALID_CREDENTIALS);
  public static final int _ACCOUNT_ALREADY_LOGGED_IN = 2;
  public static final com.java.fingrp7_java.Client.WordyGameClient.LoginResult ACCOUNT_ALREADY_LOGGED_IN = new com.java.fingrp7_java.Client.WordyGameClient.LoginResult(_ACCOUNT_ALREADY_LOGGED_IN);

  public int value ()
  {
    return __value;
  }

  public static com.java.fingrp7_java.Client.WordyGameClient.LoginResult from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LoginResult (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LoginResult
