package com.java.fingrp7_java.Client.WordyGameClient;


/**
* WordyGameClient/LoginResultHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

abstract public class LoginResultHelper
{
  private static String  _id = "IDL:WordyGameClient/LoginResult:1.0";

  public static void insert (org.omg.CORBA.Any a, com.java.fingrp7_java.Client.WordyGameClient.LoginResult that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.java.fingrp7_java.Client.WordyGameClient.LoginResult extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.java.fingrp7_java.Client.WordyGameClient.LoginResultHelper.id (), "LoginResult", new String[] { "SUCCESS", "INVALID_CREDENTIALS", "ACCOUNT_ALREADY_LOGGED_IN"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.java.fingrp7_java.Client.WordyGameClient.LoginResult read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.java.fingrp7_java.Client.WordyGameClient.LoginResult.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.java.fingrp7_java.Client.WordyGameClient.LoginResult value)
  {
    ostream.write_long (value.value ());
  }

}
