package com.java.fingrp7_java.Client.WordyGameClient;


/**
* WordyGameClient/WordyGamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

public final class WordyGamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public WordyGamePlayer ()
  {
  } // ctor

  public WordyGamePlayer (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class WordyGamePlayer
