package com.java.fingrp7_java.Client.WordyGameClient;

/**
* WordyGameClient/WordyGameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

public final class WordyGameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.java.fingrp7_java.Client.WordyGameClient.WordyGameServer value = null;

  public WordyGameServerHolder ()
  {
  }

  public WordyGameServerHolder (com.java.fingrp7_java.Client.WordyGameClient.WordyGameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.java.fingrp7_java.Client.WordyGameClient.WordyGameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.java.fingrp7_java.Client.WordyGameClient.WordyGameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.java.fingrp7_java.Client.WordyGameClient.WordyGameServerHelper.type ();
  }

}
