package com.java.fingrp7_java.Client.WordyGameClient;


/**
* WordyGameClient/WordyGameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

public interface WordyGameServerOperations 
{
  com.java.fingrp7_java.Client.WordyGameClient.LoginResult login (String username, String password);
  void logout (String username);
  void playGame (String username);
  String[] getLongestWords ();
  String[] getTopPlayers ();
} // interface WordyGameServerOperations
