package com.java.fingrp7_java.Client.WordyGameClient;


/**
* WordyGameClient/WordyGameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:33:03 PM SGT
*/

public interface WordyGameServer extends WordyGameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordyGameServer
