-- MySQL Script generated by MySQL Workbench
-- Fri Apr 28 08:56:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wordy_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wordy_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordy_schema` ;
USE `wordy_schema` ;

-- -----------------------------------------------------
-- Table `wordy_schema`.`Word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordy_schema`.`Word` ;

CREATE TABLE IF NOT EXISTS `wordy_schema`.`Word` (
  `gameID` INT NOT NULL,
  `roundNum` INT NOT NULL,
  `userID` INT NOT NULL,
  `words` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordy_schema`.`Round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordy_schema`.`Round` ;

CREATE TABLE IF NOT EXISTS `wordy_schema`.`Round` (
  `gameID` INT NOT NULL,
  `roundNum` INT NOT NULL,
  `roundWin` VARCHAR(45) NULL,
  `longestWord` VARCHAR(45) NULL,
  PRIMARY KEY (`gameID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordy_schema`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordy_schema`.`Game` ;

CREATE TABLE IF NOT EXISTS `wordy_schema`.`Game` (
  `gameID` INT NOT NULL,
  `gameWinner` VARCHAR(45) NULL,
  PRIMARY KEY (`gameID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordy_schema`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordy_schema`.`Users` ;

CREATE TABLE IF NOT EXISTS `wordy_schema`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
