package WordyGameServer;

/**
* WordyGameServer/WordyGameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:44:05 PM SGT
*/

public final class WordyGameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGameServer value = null;

  public WordyGameServerHolder ()
  {
  }

  public WordyGameServerHolder (WordyGameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGameServerHelper.type ();
  }

}
