module WordyGame {

  typedef sequence<string> StringSeq;

  enum CredentialsResult {SUCCESS, INVALID_CREDENTIALS, ACCOUNT_ALREADY_LOGGED_IN, USERNAME_TAKEN, SERVER_UNAVAILABLE};
  enum WordValidation{WORD_LESS_THAN_FIVE_LETTERS, INVALID_WORD};

  struct WordyGamePlayer {
    string username;
    long wins;
  };

  interface WordyGameServer {
    CredentialsResult login(in string username, in string password); // Connect
    CredentialsResult signUp(); // 1
    void logout(in string username);
    StringSeq playGame(in string username);
    boolean checkWord(in string word);

    StringSeq getLongestWords();
    StringSeq getTopPlayers();
  };

  exception NoPlayersAvailable {
    string reason;
  };

  exception InvalidWord {
    string reason;
  };


  exception loginFailed{
    string reason;
  };
};
