module WordyGame {

  typedef sequence<string> StringSeq;

  enum CredentialsResult {SUCCESS, INVALID_CREDENTIALS, ACCOUNT_ALREADY_LOGGED_IN, USERNAME_TAKEN, SERVER_UNAVAILABLE};
  enum WordValidation{WORD_LESS_THAN_FIVE_LETTERS, INVALID_WORD};
  enum LobbyStatus{JOINED_A_GAME, NEW_GAME};

  struct WordyGamePlayer {
    long id;
    long wins;
  };

  interface WordyGameServer {
    CredentialsResult login(in string username, in string password); // Connect
    void logout(in string username);
    LobbyStatus playGame(in WordyGamePlayer username);
    boolean checkWord(in string word);

    StringSeq getLongestWords();
    StringSeq getTopPlayers();
  };

  exception NoPlayersAvailable {
    string reason;
  };

  exception InvalidWord {
    string reason;
  };

  exception LoginFailed{
    string reason;
  };
};
