package com.java.fingrp7_java.Server.WordyGameServer;

/**
* WordyGameServer/LoginResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:44:05 PM SGT
*/

public final class LoginResultHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginResult value = null;

  public LoginResultHolder ()
  {
  }

  public LoginResultHolder (LoginResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginResultHelper.type ();
  }

}
