package com.java.fingrp7_java.Server.WordyGameServer;


/**
* WordyGameServer/LoginResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:44:05 PM SGT
*/

public class LoginResult implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static LoginResult[] __array = new LoginResult[__size];

  public static final int _SUCCESS = 0;
  public static final LoginResult SUCCESS = new LoginResult(_SUCCESS);
  public static final int _INVALID_CREDENTIALS = 1;
  public static final LoginResult INVALID_CREDENTIALS = new LoginResult(_INVALID_CREDENTIALS);
  public static final int _ACCOUNT_ALREADY_LOGGED_IN = 2;
  public static final LoginResult ACCOUNT_ALREADY_LOGGED_IN = new LoginResult(_ACCOUNT_ALREADY_LOGGED_IN);

  public int value ()
  {
    return __value;
  }

  public static LoginResult from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LoginResult (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LoginResult
