package com.java.fingrp7_java.Server.WordyGameServer;

/**
* WordyGameServer/WordyGamePlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:44:05 PM SGT
*/

public final class WordyGamePlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGamePlayer value = null;

  public WordyGamePlayerHolder ()
  {
  }

  public WordyGamePlayerHolder (WordyGamePlayer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGamePlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGamePlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGamePlayerHelper.type ();
  }

}
