package com.java.fingrp7_java.Server.WordyGameServer;


/**
* WordyGameServer/WordyGameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyGame.idl
* Monday, April 17, 2023 4:44:05 PM SGT
*/

public interface WordyGameServerOperations 
{
  LoginResult login (String username, String password);
  void logout (String username);
  void playGame (String username);
  String[] getLongestWords ();
  String[] getTopPlayers ();
} // interface WordyGameServerOperations
